### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by manuel-di-iorio** [manuel-di-iorio/status.js#1]
## TODO LIST

- [ ] Pre-rendering of the service status (to avoid the first waiting on page load)

- [ ] OG meta tags with the quick operational status (useful for link sharing)

- [ ] Expandable sections with an (+) icon

- [ ] Tooltip icon for the services or sections

- [ ] Tag labels in the services description

- [ ] Automatically email alerts when one or multiple services are not operational. 
Will only send new alerts for new downtimes when all the services will be operational again, with a timespan of 30 minutes (configurable) between every alert. 
Will use `Nodemailer` as primary module, but it will be configurable with a custom service provider (e.g. sending push notifications instead of emails)

- [ ] Automation tool for JS/CSS optimization process

- [ ] Test units and coverage both for frontend and backend

### Later Todo

- [ ] Data stored upon a multi-database ORM (eg. http://www.camintejs.com or http://1602.github.io/jugglingdb) (?)

- [ ] Past incidents (with Markdown style)

- [ ] Login to manage the things directly online (insert/update incidents, change the status of a service)

- [ ] Scheduled maintenance box
